name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t finnick5/test:v1.0.3
    - name: Login
      run: docker login -u finnick5 -p ${{ secrets.DOCKER_KEY }}
    - name: Publish
      run: docker push finnick5/test:v1.0.3