name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche à chaque push sur main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker and Buildx versions
        run: |
          docker --version
          docker buildx version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=finnick5/molybot
          VERSION=${{ env.VERSION }}

          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Clean up Docker images
        run: |
          IMAGE_NAME=finnick5/molybot
          VERSION=${{ env.VERSION }}
          docker rmi $IMAGE_NAME:$VERSION
          docker rmi $IMAGE_NAME:latest